### PR TITLE
[TASK] Use dependency injection in the SessionController

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
This is blocked by https://github.com/phpList/phplist4-core/pull/208, I think.

**Comment by oliverklee** [comment]
This now is not blocked anymore and is ready for review.

**Comment by samtuke** [comment]
CI test failed due to database access configuration

**Comment by oliverklee** [comment]
The build works fine on my local machine, and on Travis it fails only with PHP 7, not with PHP 7.1 or 7.2. I'm currently investigating this.

**Comment by oliverklee** [comment]
I've also created PR #50 as quick fix to get the master to green (once the PHP-7-related build failure has been fixed) before we switch the controllers to DI.

**Comment by samtuke** [comment]
As you say, it passes on other PHP versions, so approved

**Comment by oliverklee** [comment]
Merging. I'll take care of the build failure separately.

**Pull request merged**
